name: Create Open WebUI Release Asset

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  create-asset:
    # ⚠️ Use the powerful runner for this one-time job
    runs-on: ubuntu-latest-16-cores 

    steps:
      - name: Check out Open WebUI source code
        uses: actions/checkout@v4
        with:
          repository: open-webui/open-webui
          ref: 'v0.6.23' # Pin to the exact version you need

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build the frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Package the artifact
        run: |
          # Create a directory to hold the assets
          mkdir -p release_assets/backend
          # Copy the built frontend and the backend into it
          cp -R frontend/build release_assets/
          cp -R backend/* release_assets/backend/
          # Create the compressed archive
          tar -czvf webui-v0.6.23.tar.gz -C release_assets .

      - name: Create Release and Upload Asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v0.6.23 \
            --title "Open WebUI v0.6.23 Pre-built Artifact" \
            --notes "Contains pre-built frontend and backend files for Docker builds." \
            webui-v0.6.23.tar.gz
