name: Create Open WebUI Release Asset

# This allows you to run the workflow manually from the GitHub Actions tab
on:
  workflow_dispatch:

jobs:
  build-and-release-asset:
    name: Build and Release WebUI Artifact
    # ⚠️ This job MUST run on a powerful runner to handle the npm build
    runs-on: ubuntu-latest-16-cores

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the asset-builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          # This explicitly tells Docker to use your asset builder file
          file: ./Dockerfile.asset-builder
          # We don't push this image, we just load it locally to extract the file
          load: true
          tags: open-webui-asset-builder:latest

      - name: Extract artifact from the builder image
        run: |
          # Create a temporary container from the image we just built
          CONTAINER_ID=$(docker create open-webui-asset-builder:latest)
          # Copy the finished archive from the container to the runner's workspace
          docker cp "${CONTAINER_ID}:/webui-v0.6.23.tar.gz" .
          # Clean up the temporary container
          docker rm -v "${CONTAINER_ID}"

      - name: Create GitHub Release and Upload Asset
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v0.6.23 \
            --title "Open WebUI v0.6.23 Pre-built Artifact" \
            --notes "Contains pre-built frontend and backend files for the main Docker build." \
            webui-v0.6.23.tar.gz
