name: Create Open WebUI Release Asset

on:
  workflow_dispatch:

jobs:
  build-and-release-asset:
    name: Build and Release WebUI Artifact
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the asset-builder image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.asset-builder
          load: true
          tags: open-webui-asset-builder:latest

      - name: Extract artifact from the builder image
        run: |
          CONTAINER_ID=$(docker create open-webui-asset-builder:latest)
          docker cp "${CONTAINER_ID}:/webui-v0.6.23.tar.gz" .
          docker rm -v "${CONTAINER_ID}"

      # ✅ FIX: Install the GitHub CLI on the self-hosted runner
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt-get update \
          && sudo apt-get install gh -y

      - name: Create GitHub Release and Upload Asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v0.6.23 \
            --title "Open WebUI v0.6.23 Pre-built Artifact" \
            --notes "Contains pre-built frontend and backend files for the main Docker build." \
            webui-v0.6.23.tar.gz
