name: Main Docker Build and Push

on:
  push:
    branches:
      - main
      # Add your feature branch here to have it build automatically on push
      - 'feature/**'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Main Image
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clean up Docker resources
        run: |
          docker system prune -af
          docker volume prune -f

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Generate Docker tag
        id: generate_tags
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_OUTPUT
          else
            # Sanitize the branch name to make it a valid Docker tag
            # Replaces '/' with '-' (e.g., 'feature/new-build' -> 'feature-new-build')
            SANITIZED_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
            echo "DOCKER_TAG=${SANITIZED_BRANCH}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sjpgwh/mixed-llm:${{ steps.generate_tags.outputs.DOCKER_TAG }}
          cache-from: type=gha
          # --- CHANGE: Switched caching mode from 'max' to 'min' to reduce cache size ---
          cache-to: type=gha,mode=min
